export const SETCURRENT = 'appendCustomerPubCurrent'
export const PAGESIZE = 'appendCustomerPubPageSize'
export const SETLIST = 'setCustomerPubList'
export const PAGINATION = 'CustomerPubPaginationProps'
export const INIT = 'appendCustomerPubInit'