export const SETCURRENT = 'appendInstituteAllSetCurrent'
export const PAGESIZE = 'appendInstituteAllPageSize'
export const SETLIST = 'setInstituteAllList'
export const PAGINATION = 'InstituteAllPaginationProps'
export const INIT = 'appendInstituteAllInit'