export const SETCURRENT = 'appendInstituteAllSetCurrent'
export const PAGESIZE = 'appendInstituteAllPageSize'
export const SETLIST = 'setInstituteAllRankList'
export const PAGINATION = 'InstituteAllRankPaginationProps'
export const INIT = 'appendInstituteAllInit'