export const SETCURRENT = 'appendCustomerTodayCurrent'
export const PAGESIZE = 'appendCustomerTodayPageSize'
export const SETLIST = 'setCustomerTodayList'
export const PAGINATION = 'CustomerTodayPaginationProps'
export const INIT = 'appendCustomerTodayInit'