export const SETCURRENT = 'appendCustomerSelectSetCurrent'
export const PAGESIZE = 'appendCustomerSelectPageSize'
export const SETLIST = 'setCustomerSelectList'
export const PAGINATION = 'CustomerSelectPaginationProps'
export const INIT = 'appendCustomerSelectInit'