export const SETCURRENT = 'appendCustomerMeSetCurrent'
export const PAGESIZE = 'appendCustomerMePageSize'
export const SETLIST = 'setCustomerMeList'
export const PAGINATION = 'CustomerMePaginationProps'
export const INIT = 'appendCustomerMeInit'