export const SETCURRENT = 'appendCustomerNotCurrent'
export const PAGESIZE = 'appendCustomerNotPageSize'
export const SETLIST = 'setCustomerNotList'
export const PAGINATION = 'CustomerNotPaginationProps'
export const INIT = 'appendCustomerNotInit'