export const SETCURRENT = 'appendCustomerReserveSetCurrent'
export const PAGESIZE = 'appendCustomerReservePageSize'
export const SETLIST = 'setCustomerReserveList'
export const PAGINATION = 'CustomerReservePaginationProps'
export const INIT = 'appendCustomerReserveInit'