export const SETCURRENT = 'appendReserveSetCurrent'
export const PAGESIZE = 'appendReservePageSize'
export const SETLIST = 'setReserveRankList'
export const PAGINATION = 'ReserveRankPaginationProps'
export const INIT = 'appendReserveInit'