export const SETCURRENT = 'appendInstituteNotSetCurrent'
export const PAGESIZE = 'appendInstituteNotPageSize'
export const SETLIST = 'setInstituteNotList'
export const PAGINATION = 'InstituteNotPaginationProps'
export const INIT = 'appendInstituteNotInit'