export const SETCURRENT = 'appendCustomerFormerCurrent'
export const PAGESIZE = 'appendCustomerFormerPageSize'
export const SETLIST = 'setCustomerFormerList'
export const PAGINATION = 'CustomerFormerPaginationProps'
export const INIT = 'appendCustomerFormerInit'