export const SETCURRENT = 'appendInstituteExperienceSetCurrent'
export const PAGESIZE = 'appendInstituteExperiencePageSize'
export const SETLIST = 'setInstituteExperienceList'
export const PAGINATION = 'InstituteExperiencePaginationProps'
export const INIT = 'appendInstituteExperienceInit'